# Generated by Django 5.2.9 on 2025-12-07 14:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import user_module.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoleIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('FREELANCER', 'Freelancer'), ('CLIENT', 'Client')], max_length=10, unique=True)),
                ('next_id', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Role ID Counter',
                'verbose_name_plural': 'Role ID Counters',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('FREELANCER', 'Freelancer'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('warnings', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', user_module.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_module.user',),
            managers=[
                ('objects', user_module.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_module.user',),
            managers=[
                ('objects', user_module.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_module.user',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_module_email_dcc5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_module_role_ce7ad2_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'FREELANCER', 'CLIENT'])), name='valid_user_role'),
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_module.freelancer')),
                ('payout_mpesa_code', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user'], name='user_module_rated_u_abfa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rater'], name='user_module_rater_i_359160_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'rated_user')},
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='categories',
            field=models.ManyToManyField(related_name='freelancer_categories', to='jobs.category'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='freelancer_profiles', to='jobs.subjectarea'),
        ),
    ]
