# Generated by Django 5.2.9 on 2025-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='payout_mpesa_code',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='freelancer_categories', to='jobs.category'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='freelancer_profiles', to='jobs.subjectarea'),
        ),
    ]
