# Generated by Django 5.2.9 on 2025-12-07 17:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_remove_freelancerprofile_payout_mpesa_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief introduction about yourself'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Currently available for new jobs'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='max_jobs_concurrent',
            field=models.PositiveIntegerField(default=3, help_text='Maximum jobs you can handle simultaneously'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='payout_preference',
            field=models.CharField(choices=[('MPESA', 'M-Pesa')], default='MPESA', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
