# Generated by Django 5.2.9 on 2025-12-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_alter_admin_options_freelancerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, help_text='Public display name', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline/headline', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken')),
                ('about', models.TextField(blank=True, help_text='Rich text bio/about section')),
                ('intro_video_url', models.URLField(blank=True, help_text='URL to intro video', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_public', models.BooleanField(default=True, help_text='Profile visible to public')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(help_text='Certification name', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Issuing organization', max_length=200)),
                ('issue_year', models.PositiveIntegerField(help_text='Year obtained')),
                ('expiry_year', models.PositiveIntegerField(blank=True, help_text='Expiry year (if applicable)', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='Verification URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_year'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='University/School name', max_length=200)),
                ('degree', models.CharField(help_text='Degree/Qualification', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='Major/Field of study', max_length=200)),
                ('start_year', models.PositiveIntegerField(help_text='Start year')),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Graduation year', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying')),
                ('grade', models.CharField(blank=True, help_text='GPA/Grade', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-is_current', '-graduation_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('project_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/')),
                ('client_name', models.CharField(blank=True, help_text='Client name', max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Project tags/skills used')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on featured portfolio')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-is_featured', 'order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title/position', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=100)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave empty if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('description', models.TextField(help_text='Job description and achievements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client/Brand name', max_length=100)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='featured_clients/')),
                ('client_url', models.URLField(blank=True, help_text='Client website URL', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of work done')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0-4 for max 5 clients)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Featured Client',
                'verbose_name_plural': 'Featured Clients',
                'ordering': ['order', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 0), ('order__lte', 4)), name='valid_featured_client_order')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Skill name', max_length=100)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_name'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
