# Generated by Django 5.2.9 on 2025-12-19 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_userprofile_certification_education_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest Session Link',
                'verbose_name_plural': 'Guest Session Links',
            },
        ),
        migrations.DeleteModel(
            name='GuestIDCounter',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='user_module_rated_u_abfa6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='user_module_rater_i_359160_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='freelancerprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='valid_rating_score'),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='shadow_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
