# Generated by Django 5.2.9 on 2026-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_taskcategory_options_and_more'),
        ('user_module', '0005_guestsession_delete_guestidcounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='freelancer_profiles', to='jobs.tasksubjectarea'),
        ),
    ]
