# Generated by Django 5.2.9 on 2026-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_rating_job_and_unique_job_rater_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
