# Generated by Django 5.2.9 on 2025-12-07 17:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('recipient_code', models.CharField(help_text='Paystack Recipient Code for bank transfer', max_length=255)),
                ('transfer_code', models.CharField(blank=True, db_index=True, help_text='Paystack Transfer Code (e.g., TRF_xxxx)', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Transfer Initiation'), ('INITIATED', 'Transfer Initiated (Paystack Queue)'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed/Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, unique=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payouts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='orders.job')),
            ],
            options={
                'verbose_name': 'Payout Transfer',
                'verbose_name_plural': 'Payout Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_update', models.CharField(max_length=255)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pay_freelancer.payout')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Log',
                'verbose_name_plural': 'Payout Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['freelancer', 'status'], name='pay_freelan_freelan_265eda_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['freelancer', 'created_at'], name='pay_freelan_freelan_bfa280_idx'),
        ),
    ]
