# Generated by Django 5.2.9 on 2026-04-09 10:24

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_job_allowed_reviews_job_reviews_used_and_more'),
        ('pay_freelancer', '0002_sync_legacy_payout_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at']},
        ),
        # I HAVE REMOVED THE REMOVEINDEX BLOCK FROM HERE
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payout',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD to withdraw', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Calculated amount in KES', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='recipient_code',
            field=models.CharField(help_text='Paystack Recipient Code', max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='transfer_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='payout',
            # Note: If this constraint causes an error on existing empty rows, 
            # we can remove it and rely on the model's clean() method instead.
            constraint=models.CheckConstraint(condition=models.Q(('usd_amount__gt', 0)), name='usd_amount_positive'),
        ),
    ]