# Generated by Django 5.2.9 on 2026-04-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_freelancer', '0003_alter_payout_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payout',
            name='pay_freelan_freelan_bfa280_idx',
        ),
    ]
