# Generated by Django 5.2.9 on 2026-04-21 15:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_freelancer', '0004_remove_payout_pay_freelan_freelan_bfa280_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='fee_amount',
        ),
        migrations.AddField(
            model_name='payout',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='destination_id',
            field=models.CharField(blank=True, help_text='Payd Destination (Phone or Wallet ID)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('PAYD', 'Payd')], default='PAYSTACK', max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='market_rate_at_request',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='recipient_code',
            field=models.CharField(blank=True, help_text='Paystack Recipient Code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
