# Generated by Django 5.2.9 on 2025-12-07 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name of the category (e.g., Computing and IT).', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from name, used for URLs and lookups.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the subject area (e.g., Data Analytics).', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from name.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of this subject area.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The parent category this subject area belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_areas', to='jobs.category')),
            ],
            options={
                'verbose_name': 'Subject Area',
                'verbose_name_plural': 'Subject Areas',
                'ordering': ['category__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_subject_per_category'), models.UniqueConstraint(fields=('slug', 'category'), name='unique_slug_per_category')],
            },
        ),
    ]
