# Generated by Django 5.2.9 on 2026-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user_module', '0005_guestsession_delete_guestidcounter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TaskCategory',
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['name'], 'verbose_name': 'TaskCategory', 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.RenameModel(
            old_name='SubjectArea',
            new_name='TaskSubjectArea',
        ),
        migrations.AlterModelOptions(
            name='tasksubjectarea',
            options={
                'verbose_name': 'Task Subject Area',
                'verbose_name_plural': 'Task Subject Areas',
                'ordering': ['category__name', 'name'],
                'constraints': [
                    models.UniqueConstraint(fields=('name', 'category'), name='unique_subject_per_category'),
                    models.UniqueConstraint(fields=('slug', 'category'), name='unique_slug_per_category'),
                ],
            },
        ),
    ]
