# Generated by Django 5.2.9 on 2026-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_taskcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubjectarea',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this subject area (Optional).'),
        ),
    ]
