# Generated by Django 5.2.9 on 2025-12-12 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSessionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guest Session Counter',
                'verbose_name_plural': 'Guest Session Counters',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Django session key for this guest', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown to freelancers (e.g., Client001)', max_length=50)),
                ('display_number', models.PositiveIntegerField(help_text='Sequential number used in display name')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('converted_to_user', models.ForeignKey(blank=True, help_text='User account created from this guest session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_guest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Session',
                'verbose_name_plural': 'Guest Sessions',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='guest_session',
            field=models.ForeignKey(blank=True, help_text='Guest session if message was sent by a guest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.guestsession'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['session_key'], name='chat_guests_session_7e1064_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['display_number'], name='chat_guests_display_2e18c6_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['is_active', '-last_seen'], name='chat_guests_is_acti_66dd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['converted_to_user'], name='chat_guests_convert_8a9512_idx'),
        ),
    ]
