# Generated by Django 5.2.9 on 2025-12-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_guest_session_models'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_job',
            field=models.ForeignKey(blank=True, help_text='Job created from this offer (if accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_offer', to='orders.job'),
        ),
    ]
