# Generated by Django 5.2.9 on 2026-02-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_created_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='offer_revisions',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
