# Generated by Django 5.2.9 on 2026-04-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_offer_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatthread'),
        ),
    ]
