# Generated by Django 5.2.9 on 2026-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatattachment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='offer_currency',
            field=models.CharField(default='USD', editable=False, max_length=3),
        ),
    ]
