# Generated by Django 5.2.9 on 2025-12-07 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name of the category (e.g., Computing and IT).', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from name, used for URLs and lookups.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional - Awaiting Payment Intent'), ('PENDING_PAYMENT', 'Pending Client Payment'), ('PAYMENT_FAILED', 'Client Payment Failed'), ('PAID', 'Paid by Client - Funds Held'), ('ASSIGNED', 'Assigned to Freelancer'), ('IN_PROGRESS', 'In Progress - Work Being Done'), ('DELIVERED', 'Delivered - Awaiting Client Review'), ('CLIENT_COMPLETED', 'Client Completed - Payout Ready'), ('DISPUTE_OPEN', 'Dispute Open'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('CANCELLED', 'Cancelled')], default='PROVISIONAL', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_marked_complete_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('paystack_authorization_url', models.URLField(blank=True, max_length=500, null=True)),
                ('paystack_status', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.category')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(blank=True, limit_choices_to={'role': 'FREELANCER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED_REFUND', 'Resolved - Refunded'), ('RESOLVED_PAID', 'Resolved - Paid to Freelancer')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_resolution_notes', models.TextField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='jobs/assignments/')),
                ('plag_report', models.FileField(upload_to='jobs/plagiarism_reports/')),
                ('ai_report', models.FileField(upload_to='jobs/ai_reports/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='orders.job')),
            ],
            options={
                'verbose_name_plural': 'Job Submissions',
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the subject area (e.g., Data Analytics).', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from name.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of this subject area.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The parent category this subject area belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_areas', to='orders.category')),
            ],
            options={
                'verbose_name': 'Subject Area',
                'verbose_name_plural': 'Subject Areas',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='subject_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.subjectarea'),
        ),
        migrations.AddConstraint(
            model_name='subjectarea',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='jobs_unique_subject_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subjectarea',
            constraint=models.UniqueConstraint(fields=('slug', 'category'), name='jobs_unique_slug_per_category'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='orders_job_status_c3ae76_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client'], name='orders_job_client__992a94_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['freelancer'], name='orders_job_freelan_b208c3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='orders_job_created_bcff7f_idx'),
        ),
    ]
