# Generated by Django 5.2.9 on 2026-02-22 18:38

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubjectArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['task_category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='ai_report',
            field=models.FileField(upload_to=orders.models.ai_report_upload_path),
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='assignment',
            field=models.FileField(upload_to=orders.models.assignment_upload_path),
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='plag_report',
            field=models.FileField(upload_to=orders.models.plag_report_upload_path),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['job'], name='orders_disp_job_id_124785_idx'),
        ),
        migrations.AddIndex(
            model_name='jobsubmission',
            index=models.Index(fields=['job'], name='orders_jobs_job_id_13a25e_idx'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.taskcategory'),
        ),
        migrations.AddField(
            model_name='tasksubjectarea',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_areas', to='orders.taskcategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='subject_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.tasksubjectarea'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddConstraint(
            model_name='tasksubjectarea',
            constraint=models.UniqueConstraint(fields=('name', 'task_category'), name='jobs_unique_subject_per_category'),
        ),
        migrations.AddConstraint(
            model_name='tasksubjectarea',
            constraint=models.UniqueConstraint(fields=('slug', 'task_category'), name='jobs_unique_slug_per_category'),
        ),
        migrations.DeleteModel(
            name='SubjectArea',
        ),
    ]
