# Generated by Django 5.2.9 on 2026-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_taskcategory_tasksubjectarea_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasksubjectarea',
            name='jobs_unique_subject_per_category',
        ),
        migrations.RemoveConstraint(
            model_name='tasksubjectarea',
            name='jobs_unique_slug_per_category',
        ),
        migrations.AddConstraint(
            model_name='tasksubjectarea',
            constraint=models.UniqueConstraint(fields=('name', 'task_category'), name='jobs_unique_subject_per_category'),
        ),
        migrations.AddConstraint(
            model_name='tasksubjectarea',
            constraint=models.UniqueConstraint(fields=('slug', 'task_category'), name='jobs_unique_slug_per_category'),
        ),
    ]
