# Generated by Django 5.2.9 on 2026-02-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_jobsubmission_submission_text_and_attachments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobsubmissionattachment',
            new_name='orders_jobs_submiss_6f8456_idx',
            old_name='orders_jobs_submiss_a9d2cc_idx',
        ),
    ]
