# Generated by Django 5.2.9 on 2026-02-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_orders_jobs_submiss_a9d2cc_idx_orders_jobs_submiss_6f8456_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allowed_reviews',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='job',
            name='reviews_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='revision_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
