# Generated by Django 5.2.9 on 2026-03-31 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('batch_type', models.CharField(choices=[('DIGEST', 'Digest'), ('BULK', 'Bulk'), ('SCHEDULED', 'Scheduled')], default='BULK', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('total_notifications', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('MESSAGE', 'Message'), ('JOB_CREATED', 'Job Created'), ('JOB_UPDATED', 'Job Updated'), ('JOB_CANCELLED', 'Job Cancelled'), ('JOB_COMPLETED', 'Job Completed'), ('OFFER_RECEIVED', 'Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('REVIEW_RECEIVED', 'Review Received'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], max_length=50, unique=True)),
                ('in_app_title_template', models.CharField(max_length=255)),
                ('in_app_message_template', models.TextField()),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('email_body_template', models.TextField(blank=True)),
                ('email_html_template', models.TextField(blank=True)),
                ('push_title_template', models.CharField(blank=True, max_length=255)),
                ('push_body_template', models.TextField(blank=True)),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('default_category', models.CharField(choices=[('CHAT', 'Chat'), ('JOB', 'Job'), ('PAYMENT', 'Payment'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50)),
                ('default_expires_in_hours', models.IntegerField(blank=True, help_text='Default expiration time in hours', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for all notifications')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('category_preferences', models.JSONField(blank=True, default=dict, help_text='Per-category channel preferences')),
                ('type_preferences', models.JSONField(blank=True, default=dict, help_text='Per-type channel preferences')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_timezone', models.CharField(default='UTC', max_length=50)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('digest_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('MESSAGE', 'Message'), ('JOB_CREATED', 'Job Created'), ('JOB_UPDATED', 'Job Updated'), ('JOB_CANCELLED', 'Job Cancelled'), ('JOB_COMPLETED', 'Job Completed'), ('OFFER_RECEIVED', 'Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('REVIEW_RECEIVED', 'Review Received'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], db_index=True, default='MESSAGE', max_length=50)),
                ('category', models.CharField(choices=[('CHAT', 'Chat'), ('JOB', 'Job'), ('PAYMENT', 'Payment'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('summary', models.CharField(blank=True, help_text='Short summary for push/email', max_length=500)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, help_text='Primary action link', max_length=500, null=True)),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of action buttons with label, url, and type')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for notification rendering')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('channels_sent', models.JSONField(blank=True, default=list, help_text='List of channels this notification was sent to')),
                ('delivery_status', models.JSONField(blank=True, default=dict, help_text='Delivery status per channel')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Schedule notification for future delivery', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiration time for notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationbatch')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_7b1202_idx'), models.Index(fields=['scheduled_for', 'created_at'], name='notificatio_schedul_721088_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
